<a href="https://colab.research.google.com/github/bokkeunyu/Test1_matrix/blob/main/Ch2_Matrix_Basic_test2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

# 데이터 불러오기

## 행렬 연산의 기초

In [4]:
A = np.array([[2, 5, 4],  # 2차원 행렬 A, B 생성
              [1, 3, 5],
              [8, 9, 0]])

B = np.array([[1, 5, 0],
              [3, 8, 3],
              [4, 2, 7]])

A_dim = np.ndim(A)  #A행렬의 차원
A_shp = np.shape(A) #A행렬의 행과 열의 갯수
A_sz = np.size(A)   #A행렬의 원소의 갯수

print('A : \n', A)
print('B : \n', B)
print('A행렬의 차원 : \n', A_dim)
print('A행렬의 행과 열의 갯수 : \n', A_shp)
print('A행렬의 총원소 갯수 : \n', A_sz)

A : 
 [[2 5 4]
 [1 3 5]
 [8 9 0]]
B : 
 [[1 5 0]
 [3 8 3]
 [4 2 7]]
A행렬의 차원 : 
 2
A행렬의 행과 열의 갯수 : 
 (3, 3)
A행렬의 총원소 갯수 : 
 9


In [ ]:
A_B_sm = A + B  # 행렬의 합
A_B_dc = A - B  # 행렬의 차

print('행렬A와 행렬B 의 합 : \n', A_B_sm,'\n')
print('행렬A와 행렬B 의 차 : \n', A_B_dc)

행렬A와 행렬B 의 합 : 
 [[ 3 10  4]
 [ 4 11  8]
 [12 11  7]] 

행렬A와 행렬B 의 차 : 
 [[ 1  0  4]
 [-2 -5  2]
 [ 4  7 -7]]


In [5]:
Cab = A.dot(B)  #AB
Cba = B.dot(A)  #BA
CAB = A*B       #A*B(행렬원소간의 곱)

print('AB : \n', Cab, '\n')
print('BA : \n', Cba, '\n')
print('A*B : \n', CAB)

AB : 
 [[ 33  58  43]
 [ 30  39  44]
 [ 35 112  27]] 

BA : 
 [[ 7 20 29]
 [38 66 52]
 [66 89 26]] 

A*B : 
 [[ 2 25  0]
 [ 3 24 15]
 [32 18  0]]


In [6]:
A_inv = np.linalg.inv(A)  # A의 역행렬 구하기
B_inv = np.linalg.inv(B)  # B의  역행렬 구하기
At = A.T  # A의 전치행렬 구하기
Bt = B.T  # B의 전치행렬 구하기

print('A의 역행렬 A-1 : \n', A_inv, '\n')
print('B의 역행렬 B-1 : \n', B_inv, '\n')
print('A의 전치행렬 At : \n', At, '\n')
print('B의 전치행렬 Bt : \n', Bt)

A의 역행렬 A-1 : 
 [[-0.9   0.72  0.26]
 [ 0.8  -0.64 -0.12]
 [-0.3   0.44  0.02]] 

B의 역행렬 B-1 : 
 [[10.  -7.   3. ]
 [-1.8  1.4 -0.6]
 [-5.2  3.6 -1.4]] 

A의 전치행렬 At : 
 [[2 1 8]
 [5 3 9]
 [4 5 0]] 

B의 전치행렬 Bt : 
 [[1 3 4]
 [5 8 2]
 [0 3 7]]


In [7]:
I = np.eye(3) # 단위행렬
Z = np.zeros((3,3))   # 영 행렬
One = np.ones((3,3)) # 모든 요소가 1인 행렬
Diag = np.diag(A)   # 행렬의 대각요소 추출

print('단위행렬 : \n', I, '\n')
print('영행렬 : \n', Z, '\n')
print('모든 요소가 1인 행렬 : \n', One, '\n')
print('행렬의 대각요소 : \n', Diag)

단위행렬 : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

영행렬 : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

모든 요소가 1인 행렬 : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

행렬의 대각요소 : 
 [2 3 0]


In [10]:
A_last_row = A[-1, :]   # 마지막 행 선택
A_last_col = A[:,-1]    # 마지막 열 선택
A_r3_c1 = A[0:3,0:1]  #  3행 1열 선택(0은 생략 가능)

print('A 행렬의 마지막 행 : \n', A_last_row, '\n')
print('A 행렬의 마직막 열 : \n', A_last_col, '\n')
print('A 행렬의 3행 1열 \n', A_r3_c1)

A 행렬의 마지막 행 : 
 [8 9 0] 

A 행렬의 마직막 열 : 
 [4 5 0] 

A 행렬의 3행 1열 
 [[2]
 [1]
 [8]]


In [13]:
A_rp = np.tile(A_last_row, reps=[4,1])   # A 마지막행 4번 반복
A_tot_sm = A.sum()   # 행렬의 모든 원소 합
A_row_sm = A.sum(axis=0,keepdims=True)   # 행렬의 행합
A_col_sm = A.sum(axis=1, keepdims=True)  # 행렬의 열합
A_row_sm_1d = A.sum(axis=0)   # 행렬의 행합을 1차원으로 나타냄

print('A행렬의 마지막행 4번 반복 : \n', A_rp, '\n')
print('A행렬의 모든 원소 합 : \n', A_tot_sm, '\n')
print('A행렬의 행합 : \n', A_row_sm, '\n')
print('A행렬의 열합 : \n', A_col_sm, '\n')
print('A행렬의 행합을 1차원으로 표시 : \n', A_row_sm_1d)

A행렬의 마지막행 4번 반복 : 
 [[8 9 0]
 [8 9 0]
 [8 9 0]
 [8 9 0]] 

A행렬의 모든 원소 합 : 
 37 

A행렬의 행합 : 
 [[11 17  9]] 

A행렬의 열합 : 
 [[11]
 [ 9]
 [17]] 

A행렬의 행합을 1차원으로 표시 : 
 [11 17  9]


In [14]:
A_B_vt = np.concatenate((A, B), axis=0)
A_B_hz = np.concatenate((A, B), axis=1)

print('행렬 수직으로 합치기 : \n', A_B_vt, '\n')
print('행렬 수평으로 합치기 : \n', A_B_hz)

행렬 수직으로 합치기 : 
 [[2 5 4]
 [1 3 5]
 [8 9 0]
 [1 5 0]
 [3 8 3]
 [4 2 7]] 

행렬 수평으로 합치기 : 
 [[2 5 4 1 5 0]
 [1 3 5 3 8 3]
 [8 9 0 4 2 7]]
